# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aule', models.CharField(default='', max_length=100)),
                ('max_iscritti', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('studenti_referenti', models.CharField(max_length=100)),
                ('descrizione', models.TextField(blank=True)),
                ('classi_autori', models.CharField(default='', max_length=10)),
                ('progressivo', models.BooleanField(default=False)),
                ('f1', models.BooleanField(default=False)),
                ('f2', models.BooleanField(default=False)),
                ('f3', models.BooleanField(default=False)),
                ('f4', models.BooleanField(default=False)),
                ('f5', models.BooleanField(default=False)),
                ('f6', models.BooleanField(default=False)),
                ('f7', models.BooleanField(default=False)),
                ('f8', models.BooleanField(default=False)),
                ('f9', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('aule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Iscrizione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('corso1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso1', to='app.Corso')),
                ('corso2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso2', to='app.Corso')),
                ('corso3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso3', to='app.Corso')),
                ('corso4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso4', to='app.Corso')),
                ('corso5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso5', to='app.Corso')),
                ('corso6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso6', to='app.Corso')),
                ('corso7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso7', to='app.Corso')),
                ('corso8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso8', to='app.Corso')),
                ('corso9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corso9', to='app.Corso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
