# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='richieste_particolari',
            field=models.CharField(blank=True, default=b'', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corso',
            name='classi_autori',
            field=models.CharField(default=b'', max_length=40),
        ),
    ]
