# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171202_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corso',
            name='richieste_particolari',
        ),
    ]
