# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_corso_convalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='corso',
            name='esperti_esterni',
            field=models.CharField(blank=True, default=b'', max_length=100, null=True),
        ),
    ]
