# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_corso_esperti_esterni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aule'},
        ),
        migrations.AlterModelOptions(
            name='corso',
            options={'verbose_name': 'Corso', 'verbose_name_plural': 'Corsi'},
        ),
        migrations.AlterModelOptions(
            name='iscrizione',
            options={'verbose_name': 'Iscrizione', 'verbose_name_plural': 'Iscrizioni'},
        ),
        migrations.RemoveField(
            model_name='corso',
            name='studenti_referenti',
        ),
        migrations.AddField(
            model_name='corso',
            name='studente_referente1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corso',
            name='studente_referente2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corso',
            name='studente_referente3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corso',
            name='studente_referente4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corso',
            name='studente_referente5',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corso',
            name='classi_autori',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='corso',
            name='esperti_esterni',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
