# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180826_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='studente_referente1',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corso',
            name='studente_referente2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corso',
            name='studente_referente3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corso',
            name='studente_referente4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corso',
            name='studente_referente5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente5', to=settings.AUTH_USER_MODEL),
        ),
    ]
