# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180826_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='studente_referente1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studente_referente1', to=settings.AUTH_USER_MODEL),
        ),
    ]
