# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-26 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_approvazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvazione',
            name='alunno',
        ),
        migrations.RemoveField(
            model_name='approvazione',
            name='corso',
        ),
        migrations.RenameField(
            model_name='corso',
            old_name='convalida',
            new_name='convalida1',
        ),
        migrations.AddField(
            model_name='corso',
            name='convalida2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='convalida3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='convalida4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corso',
            name='convalida5',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Approvazione',
        ),
    ]
